# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ab8d603b09729347027ac1e392a403946b39b2e7029bb14ca86beeee9be93143a892a494916ad460b9c35f59d27cde0d480e8c4a089d920a3040a299fb79b7

test:
  secret_key_base: daa4b6c4961ce10d447450c96b3e864be6acdf45f205454f379945da5d288d3a41fb18cd234becc3f9193a39da82463e29ed7373e3476d3d34e4a9f503f5a291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
